# Generated by Django 3.0.8 on 2020-09-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0002_auto_20200926_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=27143862),
        ),
    ]
