# Generated by Django 3.0.8 on 2020-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0005_auto_20201001_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=27577699),
        ),
    ]
