# Generated by Django 3.0.8 on 2020-10-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0008_auto_20201003_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dataAdded',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imageUrl',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=37070489),
        ),
    ]
