# Generated by Django 3.0.8 on 2020-10-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0009_auto_20201003_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=94117747),
        ),
    ]
