# Generated by Django 3.0.8 on 2020-09-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dateJoined',
        ),
    ]
